disabled_rules:
- trailing_whitespace
- valid_docs
- type_name
- variable_name

excluded:
- reddift/vendor
- playground
- reddiftTests
- reddiftSample
- reddiftSampleTV

file_length:
  warning: 2000
  error: 4000

line_length:
  warning: 10000
  error: 20000

type_body_length:
  warning: 1000
  error: 2000

variable_name:
  max_length:
    warning: 50
    error: 40
  min_length:
    warning: 1
    error: 0

function_parameter_count:
  warning: 10
  error: 20

function_body_length:
  warning: 200
  error: 400

cyclomatic_complexity:
  warning: 100
  error: 150

